# --- Google Sheets 連線設定 ---
[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1Ks6m4-Nkn4BK-83pBH879eb5f6v_L3mxc6zuUMeDq9A/edit"

# 機器人憑證 (修正引號問題：前後都只有 3 個 ")
type = "service_account"
project_id = "trusty-catbird-388602"
private_key_id = "b42773d4e9c5502d9087bec5b6542684f42cb622"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDUifxXq4bjk19e
2fK80nLobKLHXRIZLAv2Akwwwe5GPOv3JBdOmsTj/6E9TKrCo+Y1vW68QwKf/pAo
A7MU8Lt+KMjbWoukzSuA0y5cWEqLPqhnukD62oLsVDJt62J5zYkGGw1C5Tp7nui0
51SYg6rMTD4ugElOVrNUhLYLLgn404JDC8TMVXnCgCMNGwomaQbso/z1EYP3o23Q
+muxoRZKK3nzkHYXJItFFipLiAJp15NC05xajWPFiUg1ASTEEAL8aHoiOckaWI9f
/vjTREtbIX+VqECzAdZPG38WCFepUhnJ0CfLxy5dVkYGgKx5OLw+vXy8roppUIxn
aivYdXe9AgMBAAECggEACPQvb5cw7YXLmn35ScUJBQRw1gHX69iOznDGOmEstRmV
KNhoVrw9cKhmPStfSn1WJ2htqpGAzMBlh4rpsKPfbADrvqQxm76ZORTB09n+zthh
+KKAfYZIjWGvWDFaP/sNpiElESfI8shnpv0pAc+g4M6SlEZgggBs8mq+3UBD4yuq
sOgTF4b1evbfPXIibyByEirWND3QKXAnc1XkXeb/pitRQA5FRwcy6ftsjQzKEe2U
J65om5VX8uVz7AB9ajgTd2tSeObjfyNkWnvLW+zy7B59ksu/BluVmK2BE8hw0GQC
dG2y495eT2R8cuNF4adhqbwxuPGWT7UbFqgAmh3iTwKBgQD4aeQO3zHCLWNl4nAX
Lw6SGEDqnqhbBJZ1c8zcr1CDEq/dDKCEts84nztYo8w3acTIZAhnAwSVTY/40VoC
h17xxwl7MFeqISLyhiDFf4ytZe8bge36gv+1u1nw/sTRKFECYSlHiZR9fanMrVpM
qi5p/oU4qtuxnwKRnSoyLruOXwKBgQDbB6AYP5sUlaF6JUfq89StKHP+uDhxjZlc
h8Rx21UfvJVF/1TdkrWQMCjKNCz5hCb6P2dy6PaA+3+qYSBr88RI33qLWfS1+UbD
CcqerwkD44/fcAXzrQ81365KpniYNCTUVy4eDn899PD+qG/9tzzoY0BBFFWfdKXG
ecovJwk3YwKBgQD2hLcinxIVHc/PUwhjqXovN0xsyOhP8tyRUErUElK20HufxSEi
svwvt61ASMSnlRoIt2SzPYZ12BPxG2jUq5xoGVpqWs4Ucm/o93xcIjjr9wVzadxN
x2SV54fZJisRWY4S63L4oCqw4lz4VmwPOq921nNEiiIdQaxd7vbp+AB+xwKBgGkg
39bDsMvQhhD6k+pR3mK+Z+56vZzDOjkPcVq0y8bP3VYbl8BCCqOKegmTwYKBy7OR
ezXMW4TNMhm1RLqL5kqT+V2pb6toWm6C5J4FpW4Ya5XzTugGyKYzFpT+EiP74zGI
JrqGesxiJMoWTqqYqMNh4BVcjTxb4LXC/yhitCnBAoGAJBSKK4OWPb1ui9TXkdXi
XkKJhgpRJT4yyKdBv3UBwaRZWa3LdbMOGnqRgrjGp17cJdTvvzhL1f2im9MvI+fg
YiJTj15bsdS63wJZgE98cotuleVVGy/62TH7EG8Ggac9Nf2MaxByub+76aDN67HL
94I1rsds40Uaddu+ItVhygQ=
-----END PRIVATE KEY-----"""
client_email = "streamlit-db-bot-945@trusty-catbird-388602.iam.gserviceaccount.com"
client_id = "114196418164755963733"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-db-bot-945%40trusty-catbird-388602.iam.gserviceaccount.com"